config/routes.rb
Rails.application.routes.draw do

  root 'reforms#index'
  get 'index' => 'reforms#index'
  get 'index' => 'reforms#search', as: :search
  get 'index' => 'index#close', as: :close
  post 'index' => 'reforms#create', as: :create
end

app/models/reform.rb
class Reform < ActiveRecord::Base
  validates_presence_of :client
  validates_presence_of :description
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/reforms_controller.rb
class ReformsController < ApplicationController

  def index
    @reforms = Reform.all
    @reform = Reform.new

    if params[:search]
      search
    end

    if params[:close]
      close
    end
  end

  def create
    @reform = Reform.new(reform_params)
    if @reform.save
      redirect_to '/index'
    else

    end
  end

  def search
    if Reform.exists?(params[:search])
      @reform_search = Reform.find(params[:search])
    end
  end

  def close
    if Reform.exists?(params[:close])
      @reform = Reform.find(params[:close])
      @reform.closed=1
      @reform.save
      redirect_to '/index'
    end
  end

  private 
  def reform_params 
    params.require(:reform).permit(:client, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reforms_helper.rb
module ReformsHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer container-fluid">
  <div class="container">
    <small>
      The <%= link_to "Power Som app", "/reforms" %>
      by <a href="https://github.com/gabriel-augusto/">Gabriel Augusto Barbosa</a>
    </small>
    <nav>
      <ul>
        <li><%= link_to "Sobre",   '#' %></li>
        <li><%= link_to "Contato", '#' %></li>
      </ul>
    </nav>
  </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>                        
      </button>
      <%= link_to "Power Som", '/reforms', id: "logo" %>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li class="active"><%= link_to "Início",   '#' %></li>
        <li><%= link_to "Sobre",   '#' %></li>
        <li><%= link_to "Contato", '#' %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Power Som</title>
    <%= stylesheet_link_tag 'application', media: 'all',
                                           'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <div class="wrapper">
      <%= render 'layouts/header' %>
      <div>
        <%= yield %>
        <%= render 'layouts/footer' %>
      </div>
    </div>
  </body>
</html>

app/views/reforms/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-6">
      <div class="row">
        <div class="col-sm-6">
          <div class="well">
            <h3> Receber alto falante </h3>
            <%= form_for @reform, :url => create_path do |f| %>
              <div class="field">
                <%= f.text_field :client, placeholder: 'Cliente', class: 'form-control' %><br>
                <%= f.text_field :description, placeholder: 'Descrição', class: 'form-control' %><br>
              </div>
              <div class="actions">
                <%= button_tag(type: 'submit', class: 'btn btn-md btn-success') do %>
                  <i class="icon-ok icon-white" /> Receber
                <% end %>
              </div>
            <% end %>
          </div>
        </div>

        <div class="col-sm-6">
          <div class="well">
            <h3> Entregar alto falante </h3>
            <%= form_tag(close_path, method: 'get') do %>
              <div class="field">
                <%= number_field_tag :close, params[:close], in: 1...10000, placeholder: 'ID', class: 'form-control' %><br>
              </div>
              <div class="actions">
                <%= button_tag(type: 'submit', class: 'btn btn-md btn-warning') do %>
                  <i class="icon-ok icon-white" /> Entregar
                <% end %>
              </div>
            <% end %>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-sm-12 center">
          <div class="well">
            <div class="row">
              <div class="col-sm-6">
                <h3>Pesquisar reforma: </h3>
              </div>
              <div class="col-sm-6 margin-special">
                <%= form_tag(search_path, method: "get") do %>
                  <div class="input-group form-inline">
                    <%= number_field_tag :search, params[:search], in: 1...10000, class: 'form-control', placeholder: "ID" %>
                    <span class="input-group-btn">
                      <div class="actions">
                        <%= button_tag(type: 'submit', class: "btn btn-default") do %>
                          <span class='glyphicon glyphicon-search'></span>
                        <% end %>
                      </div>
                    </span>
                  </div>
                <% end %>
              </div>
            </div>

            <table class="table table-striped">
              <thead>
                <tr>
                  <th>ID</th>
                  <th>Nome</th>
                  <th>Descrição</th>
                  <th>Entregue</th>
                  <th>Data de entrega</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <% if @reform_search %>
                    <td><%= @reform_search.id %></td>
                    <td><%= @reform_search.client %></td>
                    <td><%= @reform_search.description %></td>
                    <% if @reform_search.closed? %>
                      <td><span class="glyphicon glyphicon-ok" /></td>
                    <% else %>
                      <td><span class="glyphicon glyphicon-remove" /></td>
                    <% end %>
                    <td><%= @reform_search.created_at %></td>
                  <% end %>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>

    <div class="col-sm-6">
      <div class="well">
        <div class="open-reforms">
          <h3>Reformas em aberto</h3>
          <table class="table table-striped">
            <thead>
              <tr>
                <th>ID</th>
                <th>Nome</th>
                <th>Descrição</th>
                <th>Data de entrega</th>
              </tr>
            </thead>
            <tbody>
              <% @reforms.each do |reform| %>
                <% unless reform.closed? %>
                  <tr>
                    <td><%= reform.id %></td>
                    <td><%= reform.client %></td>
                    <td><%= reform.description %></td>
                    <td><%= reform.created_at %></td>
                  </tr>
                <% end %>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>